#!/bin/bash

set -euo pipefail

function print_usage {
    echo "ddig [-g <glob pattern>] <initial_pattern>"
    echo -e "\t-g <glob pattern>: filtering pattern for file names. Example: -g \"**/test/**\" to look only in test code"
    echo -e "\t<initial_pattern>: initial pattern for rg"
}

glob_parameter="**/*"

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -g)
            shift
            glob_parameter="$1"
            shift
            ;;

        -h)
            print_usage
            exit 0
            ;;
        *)
            break;
            ;;
    esac
done

rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg -g \"$glob_parameter\" --column --line-number --no-heading --color=always --smart-case --hidden"
INITIAL_QUERY="${*:-}"
fzf --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --bind 'ctrl-t:transform:[[ ! $FZF_PROMPT =~ ripgrep ]] && 
      echo "rebind(change)+change-prompt(1. ripgrep> )+disable-search+transform-query:echo \{q} >/tmp/rg-gzg-f; cat /tmp/rg-fzf-r" ||
      echo "unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
      --bind 'ctrl-y:execute-silent(printf "%s\n" {+} | xclip -sel clip)' \
      --bind 'ctrl-a:select-all,ctrl-d:deselect-all' \
      --bind 'ctrl-e:become(vim {1} +{2})' \
      --color "hl:-1:underline,hl+:-1:underline:reverse" \
      --prompt '1. ripgrep> ' \
      --delimiter : \
      --header 'CTRL-T: Switch between ripgrep/fzf | CTRL-A: Select all | CTRL-D: Deselect all | CTRL-Y: Copy all selected lines to clipboard | CTRL-E: Launch vim against selected item' \
      --preview 'bat --color=always {1} --highlight-line {2}' \
      --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
      --multi

